#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
APP="$1"; IMAGE="dokku/$APP"
echo "-----> Installing ffmpeg ..."
COMMAND=$(cat <<EOF
echo "-----> install ffmpeg (static build)"

# Strip the dead postgresql trusty-pgdg apt source (404s since trusty EOL)
sed -i '/apt.postgresql.org.*trusty-pgdg/d' /etc/apt/sources.list
rm -f /etc/apt/sources.list.d/pgdg.list /etc/apt/sources.list.d/postgresql.list

export DEBIAN_FRONTEND=noninteractive
apt-get -y update
apt-get install -y --reinstall ca-certificates
apt-get install -y wget xz-utils

cd /tmp
wget -q https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz
tar -xf ffmpeg-release-amd64-static.tar.xz
mv ffmpeg-*-amd64-static/ffmpeg /usr/local/bin/
mv ffmpeg-*-amd64-static/ffprobe /usr/local/bin/
rm -rf ffmpeg-release-amd64-static.tar.xz ffmpeg-*-amd64-static

sleep 1 # wait so that docker run has not exited before docker attach
EOF
)
id=$(docker run -d $IMAGE /bin/bash -e -c "$COMMAND")
#enable logs
docker attach $id
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null
